name: Deploy Docker Image

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Use model server build action
        uses: YunTechAi-FreeSpaceTechnic/actions@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extra_tags: ${{ github.ref_name }}
